#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:
  asr:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/k2-sherpa-onnx:0.1"
    restart: always
    ports:
      - "6006:6006/tcp"
    networks:
      - euanka

  rasa:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/euanka-rasa:0.1"
    restart: always
    ports:
      - "5005:5005/tcp"
    networks:
      - euanka


  action-server:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/euanka-rasa-action:0.1"
    restart: always
    ports:
      - "5055:5055/tcp"
    networks:
      - euanka

  llm:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/chatglm2-6b-cpp-py-all:0.1"
    restart: always
    ports:
      - "7600:7600/tcp"
    networks:
      - euanka

  tts:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/vits:0.2"
    restart: always
    ports:
      - "7860:7860/tcp"
    networks:
      - euanka

  euanka:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/euanka:0.2"
    restart: always
    depends_on:
      - asr
      - rasa
      - action-server
      - llm
      - tts
    environment:
      # docker 原本打算使用docker内部域名，但是，我的电脑分配内部网络非常慢，使用当前的部署宿主机IP
      SERVICE_ASR: "192.168.1.16"
      SERVICE_RASA: "192.168.1.16"
      SERVICE_LLM: "192.168.1.16"
      SERVICE_TTS: "192.168.1.16"
      # 对外访问的TTS服务地址，需要修改，仍是主机的IP
      APP_EXTERNAL_TTS_HOST_PORT: "192.168.1.16:7860"
    ports:
      - "8080:8080/tcp"
    networks:
      - euanka

  euanka-web:
    image: "registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/euanka-web:0.3"
    restart: always
    depends_on:
      - euanka
    environment:
      # web服务访问的基础地址，需要修改，主机IP的websocket地址
      VUE_APP_API_BASE_URL: "ws://192.168.1.16:8080/ws/chat"
    ports:
      - "80:80/tcp"
    networks:
      - euanka

networks:
  euanka:
    driver: bridge
